// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "github.com/d-ashesss/noter-bot/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// Factory is an autogenerated mock type for the Factory type
type Factory struct {
	mock.Mock
}

// NewNoteModel provides a mock function with given fields:
func (_m *Factory) NewNoteModel() *model.NoteModel {
	ret := _m.Called()

	var r0 *model.NoteModel
	if rf, ok := ret.Get(0).(func() *model.NoteModel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.NoteModel)
		}
	}

	return r0
}
